Update directory.txt
supercollider-quarks/quarks pull request #107
Opened 2021-05-21 12:32 UTC by madskjeldgaard

Add a couple of my quarks

2021-06-11 15:56 UTC, dyfer commented
Hey @madskjeldgaard I think you have a typo in the first address :)

Also, a _really_ minor thing (not worth opening a PR in the other repo) - in the `PolyBuf.quark` you have ext_dependancy instead of ext_depend**e**ncy - which was a typo in SC help for a long time...

2021-08-05 09:02 UTC, madskjeldgaard commented
should be good now @dyfer !

2021-08-05 18:38 UTC, dyfer requested changes

2021-08-05 18:38 UTC, dyfer commented on directory.txt
> +AllBuf=https://github.com/polybuf/madskjeldgaard/allbuf
This is still not a valid URL :)

2021-08-07 13:37 UTC, madskjeldgaard commented
Haha, very sorry! Fixing it now

On 05-08-2021, Marcin Pączkowski wrote:
***@***.*** requested changes on this pull request.
>
>
>
>> @@ -1,6 +1,7 @@
> 3Dj=https://github.com/supercollider-quarks/3Dj
> adclib=https://github.com/supercollider-quarks/adclib
> AllGui=https://github.com/supercollider-quarks/AllGui
>+AllBuf=https://github.com/polybuf/madskjeldgaard/allbuf
>
>This is still not a valid URL :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/supercollider-quarks/quarks/pull/107#pullrequestreview-723681361

2021-08-07 16:13 UTC, merged